public:
  myCluster:
    core.localization.config:
      releaseKey: "20200309212653-7fec91b6d277b5ab"
      configurations:
        hll.cluster.country.id: 10000
        hll.local.timezone: "Asia/Kolkata"