myAppID:
  myCluster:
    myNamespace:
      releaseKey: "20200309212653-7fec91b6d277b5ab"
      properties:
        mysql.uri: "mysql://root@localhost/mysql"
        snowflake.uri: "http://192.168.0.1/snowflake"
    myNamespace2:
      releaseKey: "20200309212653-7fec91b6d277b5ab"
      yml:
        spring:
          datasource:
            dynamic:
              p6spy: false
              primary: master